### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by gumaerc**
This is a reusable starter implementation of [`ocw-course-hugo-theme`](https://github.com/mitodl/ocw-course-hugo-theme).  To test this, clone the repo and place in some content generated by [`ocw-to-hugo`](https://github.com/mitodl/ocw-to-hugo).  `ocw-to-hugo` currently generates content in a directory structure meant to be used with `hugo-course-publisher`.  To use the content with this repo, simply copy the `.json` data template output by `ocw-to-hugo` for a single course (i.e. `18-01-single-variable-calculus-fall-2006.json`)  to the `data/courses` directory.  Then, take that course's content from the `ocw-to-hugo` output (in this case, `site/content/courses/18-01-single-variable-calculus-fall-2006/*`) and copy that to this repo's folder under `content`.  Then, run `./build.sh`  After this is complete, simply type `hugo server` and a dev server should spin up for you.  Verify that the site looks correct and links function properly.

### CODE REVIEW

**Comment by alicewriteswrongs** [comment]
is there another setup step I need to do before this will work properly? I copied over the `ocw-to-hugo` output and then got the following error when running `./build.sh`:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:webpack',
1 verbose cli   '--prefix',
1 verbose cli   '_vendor/github.com/mitodl/ocw-course-hugo-theme'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v15.3.0
4 verbose stack Error: ENOENT: no such file or directory, open '/home/alice/Code/ocw/ocw-course-hugo-starter/_vendor/github.com/mitodl/ocw-course-hugo-theme/package.json'
5 verbose cwd /home/alice/Code/ocw/ocw-course-hugo-starter
6 verbose Linux 5.9.11-arch2-1
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build:webpack" "--prefix" "_vendor/github.com/mitodl/ocw-course-hugo-theme"
8 verbose node v15.3.0
9 verbose npm  v6.14.8
10 error code ENOENT
11 error syscall open
12 error path /home/alice/Code/ocw/ocw-course-hugo-starter/_vendor/github.com/mitodl/ocw-course-hugo-theme/package.json
13 error errno -2
14 error enoent ENOENT: no such file or directory, open '/home/alice/Code/ocw/ocw-course-hugo-starter/_vendor/github.com/mitodl/ocw-course-hugo-theme/package.json'
15 error enoent This is related to npm not being able to find a file.
16 verbose exit [ -2, true ]
```

**Comment by alicewriteswrongs** [comment]
also, would it be a good idea to have the `content` and `data/courses` directories already present here, with a `.keep` file?

**Comment by gumaerc** [comment]
@aliceriot  So, a slight oversight in testing this is that since the initial PR for `ocw-course-hugo-theme` has not merged yet, it's pulling in the blank repo and trying to execute the build on it.  In order to pull in the PR commit for the theme, you'll need to replace the contents of `go.mod` with this:

```
module github.com/mitodl/ocw-course-hugo-starter@9eaf2b62ee66

go 1.13

require github.com/mitodl/ocw-course-hugo-theme v0.0.0-20201214225859-9eaf2b62ee66 // indirect
```

Afterwards, run `hugo mod clean && hugo mod tidy` and then try `./build.sh` again.

**Comment by alicewriteswrongs** [comment]
got it working! I had to manually edit the pulled-in theme to remove the `engines` declaration in `package.json` because my local node.js is `15.3.0` but after doing that I ran through the `build.sh`, built everything, and `hugo server` works great!

**Review by alicewriteswrongs — APPROVED** [review]
LGTM!

**Pull request merged**
