### PR TITLE
optional build arguments

### LINKED ISSUE #3: If yarn is required,  add to the requirements in the readme file

### LINKED ISSUE #4: output dependencies to another folder
As a user of `ocw-course-hugo-starter`, I'd like to be able to output my build artifacts to an external location instead of the default of `dist`.

### PR DESCRIPTION
**Pull request by gumaerc**
#### What are the relevant tickets?
Closes https://github.com/mitodl/ocw-course-hugo-starter/issues/4
Closes https://github.com/mitodl/ocw-course-hugo-starter/issues/3

#### What's this PR do?
This PR adds some structure to the script along with the ability to parse new options, found in the readme.

#### How should this be manually tested?
Clone and start [ocw-www](https://github.com/mitodl/ocw-www) with:

```sh
git clone git@github.com:mitodl/ocw-www.git
git fetch
git checkout cg/hugo-server-rendertodisk
yarn install
npm start
```

This will start hugo server with the `--renderToDisk` option which allows us to inject content into the running dev server.  Now, we are ready to get OCW content with [ocw-to-hugo](https://github.com/mitodl/ocw-to-hugo):

```sh
git clone git@github.com:mitodl/ocw-to-hugo.git
yarn install
node . -i private/courses -o private/output --courses course_json_examples/example_courses.json --download
```

Once the courses have downloaded and conversion has finished, we are ready to build and inject them into our running `ocw-www` site.  In your `ocw-course-hugo-starter` folder run the following, replacing `ocw-to-hugo` and `ocw-www` with your local paths to those repos:

```sh
yarn install
./build.sh -o ocw-www/site/public -c ocw-to-hugo/private/output -b //localhost:3000/courses
```

After the build is done, you should be able to browse the following course sites and any other course in `example_courses.json`:

http://localhost:3000/courses/18-06-linear-algebra-spring-2010/
http://localhost:3000/courses/12-001-introduction-to-geology-fall-2013/

### CODE REVIEW

**Comment by noisecapella** [comment]
Have you seen this error before when running `build.sh`
Screenshot from 2021-01-05 10-55-12
?

**Comment by gumaerc** [comment]
@noisecapella Yes, the issue here I think is that the version of Hugo packaged with Ubuntu is not recent enough.  I installed the most recent version (0.80.0) manually.  With older versions, `package.json` files are excluded when pulling in Hugo modules.  Can you try installing 0.80.0 and let me know if that works for you?  I'll make a note of the minimum required version.

**Comment by gumaerc** [comment]
Also, I just realized I made an oversight with this and didn't include a parameter for setting the base URL, it's still hard coded from early testing to `//localhost:3000/courses/$COURSE_ID/`.  I'll need to add an extra parameter so that can be passed into the script.

**Comment by gumaerc** [comment]
@noisecapella back to you

**Comment by noisecapella** [comment]
Did you mean to commit a change to `build.sh`? I'm not seeing any `baseUrl` argument there

**Comment by gumaerc** [comment]
@noisecapella my bad, should be all set now

**Comment by noisecapella** [comment]
I'm seeing some small modifications to `go.sum` and `go.mod` after running the build script. Should we add these to `.gitignore` or should they not be part of the repository?

**Comment by gumaerc** [comment]
@noisecapella `go.mod` can't be in gitignore, because it's what defines the project as a go module and therefore allows pulling in other hugo modules as dependencies.  Each time a new version of `ocw-course-hugo-theme` is pushed to the `main` branch, running `hugo mod get -u` will pull in the latest version and update the commit hash in `go.mod`, and `go.sum` tracks the update history.  I think we might be able to .gitignore  `go.sum`, but I'm not certain.  One benefit of all of this is that the starter will be locked to a specific version of the theme.

**Comment by gumaerc** [comment]
Actually, thinking again we could probably add both of them to .gitignore now that `go.mod` is committed in its stock state.  That might be the best option given the circumstances.

**Comment by noisecapella** [comment]
Works great! :+1:

One last optional thing: can you also add `data/course.json` to `.gitignore`?

**Review by noisecapella — APPROVED** [review]

**Pull request merged**
